language: php
dist: precise
php:
  - 5.6
  - 7.0
  - 7.1

matrix:
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update && composer install --no-interaction
  - cd tests

script: phpunit --stderr
after_script:
  - pwd
  - cd ../
##  - git init
  - git config --global user.name "yakeing"
  - git config --global user.email "yakeing@gmail.com"
  - git tag v1.2
  - git show v1.2
  - git push --force --tags --quiet "https://${TOKEN}@github.com/yakeing/php_fsockopen.git" master:master
